# Extensions GNOME 50 gérées par Fedora Setup.
# Format : UUID|nom|paquet Fedora facultatif|version|version_tag|SHA-256|activer
# Une archive officielle GNOME est utilisée lorsque le paquet est absent.

appindicatorsupport@rgcjonas.gmail.com|AppIndicator|gnome-shell-extension-appindicator|0|0|-|true
user-theme@gnome-shell-extensions.gcampax.github.com|User Themes|gnome-shell-extension-user-theme|0|0|-|false
dash-to-dock@micxgx.gmail.com|Dash to Dock|gnome-shell-extension-dash-to-dock|0|0|-|true
blur-my-shell@aunetx|Blur My Shell|gnome-shell-extension-blur-my-shell|72|69740|4b82a0a0be4f2f917bff88e0952fab4d6c347d1128e7d8487caef240b699a910|true
gsconnect@andyholmes.github.io|GSConnect|gnome-shell-extension-gsconnect|72|70399|54ae815f27e99fcc36ba38eeacd68e768db88741d72d925536fe2eb3226346e2|true
CoverflowAltTab@palatis.blogspot.com|Coverflow Alt-Tab|-|87|72770|876e303e93b9563ed030c2807c8e896deeaf3dc64c20e8694868e600071755a3|true
add-to-desktop@tommimon.github.com|Add to Desktop|-|16|69513|88b98d36bd1dd4372cf922c23be7d1bb65ef9a05f7c161bfc2c9f349375ca722|true
tiling-assistant@leleat-on-github|Tiling Assistant|-|54|68287|9b2b8ebc3eee5803d4f12b2f08b855303e91cebd70ff6d6aef3b1e7903920de1|true
ding@rastersoft.com|Desktop Icons NG|gnome-shell-extension-desktop-icons-ng|93|73926|44c1919ad828d58aa21e16acd6d6ff0c2cb5c66c4f1a34429f80e1248ad97c23|true
